### ISSUE TITLE
Crashes on page not found (404)

### ISSUE THREAD

**Issue by YannickGagnon** [logaritmdev/cortex#1]
Fails when navigating to an undefined page: wordpress.dev/foo

enqueue_styles
[https://github.com/logaritmdev/cortex/blob/master/public/class-cortex-public.php#L67](url)

enqueue_scripts
[https://github.com/logaritmdev/cortex/blob/master/public/class-cortex-public.php#L90](url)

**Comment by jpdery** [comment]
Fixed
